# Generated by Django 5.0.3 on 2024-03-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_order_payment_product_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
