# Generated by Django 5.0.3 on 2024-04-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_delete_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="website/media/products/"
            ),
        ),
    ]
